customCommands:
  containers:
    - name: bash
      attach: true
      command: "docker exec -it {{ .Container.ID }} bash"
      serviceNames: []
    - name: sh
      attach: true
      command: "docker exec -it {{ .Container.ID }} /bin/sh"
      serviceNames: []
  images:
    - name: run detached
      attach: false
      command: "docker run -d _instance {{ .Image.Name }}:{{ .Image.Tag }}"
      serviceNames: []
    - name: run interactive
      attach: true
      command: "docker run --rm -it {{ .Image.Name }}:{{ .Image.Tag }}"
      serviceNames: []
    - name: run with sh
      attach: true
      command: "docker run --rm -it --entrypoint sh {{ .Image.Name }}:{{ .Image.Tag }}"
      serviceNames: []
